steps:
  # Step 1: Compile the Go Application
  - name: 'gcr.io/cloud-builders/go'
    env: ['GOPATH=/gopath']
    args: ['build', '-o', 'main', 'main.go']

  # Step 2: Build the Docker image for the Go application
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      '${_REGION}-docker.pkg.dev/$PROJECT_ID/my-repository/hello-cloudbuild-dev:${_TAG}', # Use _REGION and _TAG
      '.'
    ]

  # Step 3: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/$PROJECT_ID/my-repository/hello-cloudbuild-dev:${_TAG}' # Use _REGION and _TAG
    ]

  # Step 4: Apply the production deployment YAML file to the production namespace
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Deploy'
    args: ['-n', 'dev', 'apply', '-f', 'dev/deployment.yaml']
    env:
    - 'CLOUDSDK_COMPUTE_REGION=${_REGION}' # Use _REGION
    - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cluster'

options:
  logging: CLOUD_LOGGING_ONLY

# Define your substitutions here
substitutions:
  _REGION: 'europe-west1' # Example: Your specific region
  _TAG: '${COMMIT_SHA}'   # Example: Use the commit SHA for the image tag
                          # Or if you tag your Git commits: _TAG: '${TAG_NAME}'
                          # Or a custom version: _TAG: 'v1.0.0'
